apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{APP_NAME}}-staging
resources:
  - namespace.yaml
  - ../base/oci-repository.yaml
  - values-configmap.yaml
  - helmrelease.yaml