apiVersion: v2
name: {{APP_NAME}}
description: Helm chart for {{APP_TITLE}} Discord Bot
type: application
version: 0.1.0
appVersion: "1.0.0"

maintainers:
  - name: {{GITHUB_ORG}}
    url: https://github.com/{{GITHUB_ORG}}

keywords:
  - discord
  - bot
  - nodejs
  - kubernetes

home: https://github.com/{{GITHUB_ORG}}/{{APP_NAME}}
sources:
  - https://github.com/{{GITHUB_ORG}}/{{APP_NAME}}

dependencies:
  - name: postgresql
    version: "16.x.x"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: redis
    version: "20.x.x"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled