{{- if .Values.secrets.gsm.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "app.fullname" . }}-secrets
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  provider: gcp
  parameters:
    secrets: |
      {{- range .Values.secrets.gsm.secrets }}
      - resourceName: "projects/{{ $.Values.secrets.gsm.projectId }}/secrets/{{ .gsmName }}/versions/latest"
        path: "{{ .secretName }}"
      {{- end }}
  secretObjects:
    - secretName: {{ include "app.fullname" . }}-gsm-secrets
      type: Opaque
      data:
        {{- range .Values.secrets.gsm.secrets }}
        - objectName: "{{ .secretName }}"
          key: "{{ .key }}"
        {{- end }}
{{- end }}